// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/feedback/feedback.proto

package feedback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeedbackVisibility represents visibility levels
type FeedbackVisibility int32

const (
	FeedbackVisibility_FEEDBACK_VISIBILITY_UNSPECIFIED FeedbackVisibility = 0
	FeedbackVisibility_FEEDBACK_VISIBILITY_PUBLIC      FeedbackVisibility = 1
	FeedbackVisibility_FEEDBACK_VISIBILITY_PRIVATE     FeedbackVisibility = 2
	FeedbackVisibility_FEEDBACK_VISIBILITY_TEAM        FeedbackVisibility = 3
)

// Enum value maps for FeedbackVisibility.
var (
	FeedbackVisibility_name = map[int32]string{
		0: "FEEDBACK_VISIBILITY_UNSPECIFIED",
		1: "FEEDBACK_VISIBILITY_PUBLIC",
		2: "FEEDBACK_VISIBILITY_PRIVATE",
		3: "FEEDBACK_VISIBILITY_TEAM",
	}
	FeedbackVisibility_value = map[string]int32{
		"FEEDBACK_VISIBILITY_UNSPECIFIED": 0,
		"FEEDBACK_VISIBILITY_PUBLIC":      1,
		"FEEDBACK_VISIBILITY_PRIVATE":     2,
		"FEEDBACK_VISIBILITY_TEAM":        3,
	}
)

func (x FeedbackVisibility) Enum() *FeedbackVisibility {
	p := new(FeedbackVisibility)
	*p = x
	return p
}

func (x FeedbackVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_feedback_feedback_proto_enumTypes[0].Descriptor()
}

func (FeedbackVisibility) Type() protoreflect.EnumType {
	return &file_api_proto_feedback_feedback_proto_enumTypes[0]
}

func (x FeedbackVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackVisibility.Descriptor instead.
func (FeedbackVisibility) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{0}
}

// FeedbackType represents types of feedback
type FeedbackType int32

const (
	FeedbackType_FEEDBACK_TYPE_UNSPECIFIED  FeedbackType = 0
	FeedbackType_FEEDBACK_TYPE_APPRECIATION FeedbackType = 1
	FeedbackType_FEEDBACK_TYPE_SUGGESTION   FeedbackType = 2
	FeedbackType_FEEDBACK_TYPE_ISSUE        FeedbackType = 3
	FeedbackType_FEEDBACK_TYPE_OTHER        FeedbackType = 4
)

// Enum value maps for FeedbackType.
var (
	FeedbackType_name = map[int32]string{
		0: "FEEDBACK_TYPE_UNSPECIFIED",
		1: "FEEDBACK_TYPE_APPRECIATION",
		2: "FEEDBACK_TYPE_SUGGESTION",
		3: "FEEDBACK_TYPE_ISSUE",
		4: "FEEDBACK_TYPE_OTHER",
	}
	FeedbackType_value = map[string]int32{
		"FEEDBACK_TYPE_UNSPECIFIED":  0,
		"FEEDBACK_TYPE_APPRECIATION": 1,
		"FEEDBACK_TYPE_SUGGESTION":   2,
		"FEEDBACK_TYPE_ISSUE":        3,
		"FEEDBACK_TYPE_OTHER":        4,
	}
)

func (x FeedbackType) Enum() *FeedbackType {
	p := new(FeedbackType)
	*p = x
	return p
}

func (x FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_feedback_feedback_proto_enumTypes[1].Descriptor()
}

func (FeedbackType) Type() protoreflect.EnumType {
	return &file_api_proto_feedback_feedback_proto_enumTypes[1]
}

func (x FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackType.Descriptor instead.
func (FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{1}
}

// UserSummary represents a minimal user reference
type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *UserSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// FeedbackDimensionScore represents dimension-level scoring
type FeedbackDimensionScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimension     string                 `protobuf:"bytes,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackDimensionScore) Reset() {
	*x = FeedbackDimensionScore{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackDimensionScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackDimensionScore) ProtoMessage() {}

func (x *FeedbackDimensionScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackDimensionScore.ProtoReflect.Descriptor instead.
func (*FeedbackDimensionScore) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *FeedbackDimensionScore) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *FeedbackDimensionScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// FeedbackReactionSummary represents reaction counts
type FeedbackReactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reactions     map[string]int32       `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackReactionSummary) Reset() {
	*x = FeedbackReactionSummary{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackReactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackReactionSummary) ProtoMessage() {}

func (x *FeedbackReactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackReactionSummary.ProtoReflect.Descriptor instead.
func (*FeedbackReactionSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *FeedbackReactionSummary) GetReactions() map[string]int32 {
	if x != nil {
		return x.Reactions
	}
	return nil
}

// FeedbackItem represents a feedback post
type FeedbackItem struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	FeedbackId    string                    `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	Author        *UserSummary              `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Content       string                    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          FeedbackType              `protobuf:"varint,4,opt,name=type,proto3,enum=feedback.FeedbackType" json:"type,omitempty"`
	Visibility    FeedbackVisibility        `protobuf:"varint,5,opt,name=visibility,proto3,enum=feedback.FeedbackVisibility" json:"visibility,omitempty"`
	Reactions     *FeedbackReactionSummary  `protobuf:"bytes,6,opt,name=reactions,proto3" json:"reactions,omitempty"`
	Dimensions    []*FeedbackDimensionScore `protobuf:"bytes,7,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	CommentsCount int32                     `protobuf:"varint,8,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp    `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackItem) Reset() {
	*x = FeedbackItem{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackItem) ProtoMessage() {}

func (x *FeedbackItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackItem.ProtoReflect.Descriptor instead.
func (*FeedbackItem) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{3}
}

func (x *FeedbackItem) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *FeedbackItem) GetAuthor() *UserSummary {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *FeedbackItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FeedbackItem) GetType() FeedbackType {
	if x != nil {
		return x.Type
	}
	return FeedbackType_FEEDBACK_TYPE_UNSPECIFIED
}

func (x *FeedbackItem) GetVisibility() FeedbackVisibility {
	if x != nil {
		return x.Visibility
	}
	return FeedbackVisibility_FEEDBACK_VISIBILITY_UNSPECIFIED
}

func (x *FeedbackItem) GetReactions() *FeedbackReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *FeedbackItem) GetDimensions() []*FeedbackDimensionScore {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *FeedbackItem) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *FeedbackItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// FeedbackComment represents a comment on feedback
type FeedbackComment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommentId       string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Author          *UserSummary           `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ParentCommentId string                 `protobuf:"bytes,5,opt,name=parent_comment_id,json=parentCommentId,proto3" json:"parent_comment_id,omitempty"` // Optional, for threading
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FeedbackComment) Reset() {
	*x = FeedbackComment{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackComment) ProtoMessage() {}

func (x *FeedbackComment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackComment.ProtoReflect.Descriptor instead.
func (*FeedbackComment) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{4}
}

func (x *FeedbackComment) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *FeedbackComment) GetAuthor() *UserSummary {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *FeedbackComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FeedbackComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FeedbackComment) GetParentCommentId() string {
	if x != nil {
		return x.ParentCommentId
	}
	return ""
}

// GetFeedRequest requests a paginated feed
type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{5}
}

func (x *GetFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFeedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetFeedResponse returns paginated feedback items
type GetFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FeedbackItem        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{6}
}

func (x *GetFeedResponse) GetResults() []*FeedbackItem {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetFeedResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetFeedbackRequest requests a specific feedback item
type GetFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackRequest) Reset() {
	*x = GetFeedbackRequest{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackRequest) ProtoMessage() {}

func (x *GetFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{7}
}

func (x *GetFeedbackRequest) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

// GetFeedbackResponse returns a feedback item
type GetFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *FeedbackItem          `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackResponse) Reset() {
	*x = GetFeedbackResponse{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackResponse) ProtoMessage() {}

func (x *GetFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackResponse.ProtoReflect.Descriptor instead.
func (*GetFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{8}
}

func (x *GetFeedbackResponse) GetFeedback() *FeedbackItem {
	if x != nil {
		return x.Feedback
	}
	return nil
}

// GetCommentsRequest requests comments for a feedback item
type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentsRequest) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *GetCommentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCommentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetCommentsResponse returns paginated comments
type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*FeedbackComment     `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_feedback_feedback_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_feedback_feedback_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommentsResponse) GetComments() []*FeedbackComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_proto_feedback_feedback_proto protoreflect.FileDescriptor

const file_api_proto_feedback_feedback_proto_rawDesc = "" +
	"\n" +
	"!api/proto/feedback/feedback.proto\x12\bfeedback\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"L\n" +
	"\x16FeedbackDimensionScore\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\tR\tdimension\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"\xa7\x01\n" +
	"\x17FeedbackReactionSummary\x12N\n" +
	"\treactions\x18\x01 \x03(\v20.feedback.FeedbackReactionSummary.ReactionsEntryR\treactions\x1a<\n" +
	"\x0eReactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xc7\x03\n" +
	"\fFeedbackItem\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12-\n" +
	"\x06author\x18\x02 \x01(\v2\x15.feedback.UserSummaryR\x06author\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.feedback.FeedbackTypeR\x04type\x12<\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x1c.feedback.FeedbackVisibilityR\n" +
	"visibility\x12?\n" +
	"\treactions\x18\x06 \x01(\v2!.feedback.FeedbackReactionSummaryR\treactions\x12@\n" +
	"\n" +
	"dimensions\x18\a \x03(\v2 .feedback.FeedbackDimensionScoreR\n" +
	"dimensions\x12%\n" +
	"\x0ecomments_count\x18\b \x01(\x05R\rcommentsCount\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe0\x01\n" +
	"\x0fFeedbackComment\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12-\n" +
	"\x06author\x18\x02 \x01(\v2\x15.feedback.UserSummaryR\x06author\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x11parent_comment_id\x18\x05 \x01(\tR\x0fparentCommentId\">\n" +
	"\x0eGetFeedRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"Y\n" +
	"\x0fGetFeedResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.feedback.FeedbackItemR\aresults\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"5\n" +
	"\x12GetFeedbackRequest\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\"I\n" +
	"\x13GetFeedbackResponse\x122\n" +
	"\bfeedback\x18\x01 \x01(\v2\x16.feedback.FeedbackItemR\bfeedback\"c\n" +
	"\x12GetCommentsRequest\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"b\n" +
	"\x13GetCommentsResponse\x125\n" +
	"\bcomments\x18\x01 \x03(\v2\x19.feedback.FeedbackCommentR\bcomments\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count*\x98\x01\n" +
	"\x12FeedbackVisibility\x12#\n" +
	"\x1fFEEDBACK_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFEEDBACK_VISIBILITY_PUBLIC\x10\x01\x12\x1f\n" +
	"\x1bFEEDBACK_VISIBILITY_PRIVATE\x10\x02\x12\x1c\n" +
	"\x18FEEDBACK_VISIBILITY_TEAM\x10\x03*\x9d\x01\n" +
	"\fFeedbackType\x12\x1d\n" +
	"\x19FEEDBACK_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFEEDBACK_TYPE_APPRECIATION\x10\x01\x12\x1c\n" +
	"\x18FEEDBACK_TYPE_SUGGESTION\x10\x02\x12\x17\n" +
	"\x13FEEDBACK_TYPE_ISSUE\x10\x03\x12\x17\n" +
	"\x13FEEDBACK_TYPE_OTHER\x10\x042\xe9\x01\n" +
	"\x0fFeedbackService\x12>\n" +
	"\aGetFeed\x12\x18.feedback.GetFeedRequest\x1a\x19.feedback.GetFeedResponse\x12J\n" +
	"\vGetFeedback\x12\x1c.feedback.GetFeedbackRequest\x1a\x1d.feedback.GetFeedbackResponse\x12J\n" +
	"\vGetComments\x12\x1c.feedback.GetCommentsRequest\x1a\x1d.feedback.GetCommentsResponseB\x1aZ\x18ethos/api/proto/feedbackb\x06proto3"

var (
	file_api_proto_feedback_feedback_proto_rawDescOnce sync.Once
	file_api_proto_feedback_feedback_proto_rawDescData []byte
)

func file_api_proto_feedback_feedback_proto_rawDescGZIP() []byte {
	file_api_proto_feedback_feedback_proto_rawDescOnce.Do(func() {
		file_api_proto_feedback_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_feedback_feedback_proto_rawDesc), len(file_api_proto_feedback_feedback_proto_rawDesc)))
	})
	return file_api_proto_feedback_feedback_proto_rawDescData
}

var file_api_proto_feedback_feedback_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_feedback_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_feedback_feedback_proto_goTypes = []any{
	(FeedbackVisibility)(0),         // 0: feedback.FeedbackVisibility
	(FeedbackType)(0),               // 1: feedback.FeedbackType
	(*UserSummary)(nil),             // 2: feedback.UserSummary
	(*FeedbackDimensionScore)(nil),  // 3: feedback.FeedbackDimensionScore
	(*FeedbackReactionSummary)(nil), // 4: feedback.FeedbackReactionSummary
	(*FeedbackItem)(nil),            // 5: feedback.FeedbackItem
	(*FeedbackComment)(nil),         // 6: feedback.FeedbackComment
	(*GetFeedRequest)(nil),          // 7: feedback.GetFeedRequest
	(*GetFeedResponse)(nil),         // 8: feedback.GetFeedResponse
	(*GetFeedbackRequest)(nil),      // 9: feedback.GetFeedbackRequest
	(*GetFeedbackResponse)(nil),     // 10: feedback.GetFeedbackResponse
	(*GetCommentsRequest)(nil),      // 11: feedback.GetCommentsRequest
	(*GetCommentsResponse)(nil),     // 12: feedback.GetCommentsResponse
	nil,                             // 13: feedback.FeedbackReactionSummary.ReactionsEntry
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_api_proto_feedback_feedback_proto_depIdxs = []int32{
	13, // 0: feedback.FeedbackReactionSummary.reactions:type_name -> feedback.FeedbackReactionSummary.ReactionsEntry
	2,  // 1: feedback.FeedbackItem.author:type_name -> feedback.UserSummary
	1,  // 2: feedback.FeedbackItem.type:type_name -> feedback.FeedbackType
	0,  // 3: feedback.FeedbackItem.visibility:type_name -> feedback.FeedbackVisibility
	4,  // 4: feedback.FeedbackItem.reactions:type_name -> feedback.FeedbackReactionSummary
	3,  // 5: feedback.FeedbackItem.dimensions:type_name -> feedback.FeedbackDimensionScore
	14, // 6: feedback.FeedbackItem.created_at:type_name -> google.protobuf.Timestamp
	2,  // 7: feedback.FeedbackComment.author:type_name -> feedback.UserSummary
	14, // 8: feedback.FeedbackComment.created_at:type_name -> google.protobuf.Timestamp
	5,  // 9: feedback.GetFeedResponse.results:type_name -> feedback.FeedbackItem
	5,  // 10: feedback.GetFeedbackResponse.feedback:type_name -> feedback.FeedbackItem
	6,  // 11: feedback.GetCommentsResponse.comments:type_name -> feedback.FeedbackComment
	7,  // 12: feedback.FeedbackService.GetFeed:input_type -> feedback.GetFeedRequest
	9,  // 13: feedback.FeedbackService.GetFeedback:input_type -> feedback.GetFeedbackRequest
	11, // 14: feedback.FeedbackService.GetComments:input_type -> feedback.GetCommentsRequest
	8,  // 15: feedback.FeedbackService.GetFeed:output_type -> feedback.GetFeedResponse
	10, // 16: feedback.FeedbackService.GetFeedback:output_type -> feedback.GetFeedbackResponse
	12, // 17: feedback.FeedbackService.GetComments:output_type -> feedback.GetCommentsResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_feedback_feedback_proto_init() }
func file_api_proto_feedback_feedback_proto_init() {
	if File_api_proto_feedback_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_feedback_feedback_proto_rawDesc), len(file_api_proto_feedback_feedback_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_feedback_feedback_proto_goTypes,
		DependencyIndexes: file_api_proto_feedback_feedback_proto_depIdxs,
		EnumInfos:         file_api_proto_feedback_feedback_proto_enumTypes,
		MessageInfos:      file_api_proto_feedback_feedback_proto_msgTypes,
	}.Build()
	File_api_proto_feedback_feedback_proto = out.File
	file_api_proto_feedback_feedback_proto_goTypes = nil
	file_api_proto_feedback_feedback_proto_depIdxs = nil
}
