// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/people/people.proto

package people

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserProfile represents a user profile
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PublicBio     string                 `protobuf:"bytes,5,opt,name=public_bio,json=publicBio,proto3" json:"public_bio,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"` // Optional role/title
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_proto_people_people_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_people_people_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_people_people_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *UserProfile) GetPublicBio() string {
	if x != nil {
		return x.PublicBio
	}
	return ""
}

func (x *UserProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SearchPeopleRequest requests people search
type SearchPeopleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPeopleRequest) Reset() {
	*x = SearchPeopleRequest{}
	mi := &file_api_proto_people_people_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPeopleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPeopleRequest) ProtoMessage() {}

func (x *SearchPeopleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_people_people_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPeopleRequest.ProtoReflect.Descriptor instead.
func (*SearchPeopleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_people_people_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPeopleRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPeopleRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchPeopleRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// SearchPeopleResponse returns paginated search results
type SearchPeopleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UserProfile         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPeopleResponse) Reset() {
	*x = SearchPeopleResponse{}
	mi := &file_api_proto_people_people_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPeopleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPeopleResponse) ProtoMessage() {}

func (x *SearchPeopleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_people_people_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPeopleResponse.ProtoReflect.Descriptor instead.
func (*SearchPeopleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_people_people_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPeopleResponse) GetResults() []*UserProfile {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchPeopleResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetRecommendationsRequest requests people recommendations
type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_api_proto_people_people_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_people_people_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_people_people_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetRecommendationsResponse returns recommendations
type GetRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*UserProfile         `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_api_proto_people_people_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_people_people_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_people_people_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*UserProfile {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_api_proto_people_people_proto protoreflect.FileDescriptor

const file_api_proto_people_people_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/people/people.proto\x12\x06people\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12\x1d\n" +
	"\n" +
	"public_bio\x18\x05 \x01(\tR\tpublicBio\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x13SearchPeopleRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"[\n" +
	"\x14SearchPeopleResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.people.UserProfileR\aresults\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"J\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"[\n" +
	"\x1aGetRecommendationsResponse\x12=\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x13.people.UserProfileR\x0frecommendations2\xb7\x01\n" +
	"\rPeopleService\x12I\n" +
	"\fSearchPeople\x12\x1b.people.SearchPeopleRequest\x1a\x1c.people.SearchPeopleResponse\x12[\n" +
	"\x12GetRecommendations\x12!.people.GetRecommendationsRequest\x1a\".people.GetRecommendationsResponseB\x18Z\x16ethos/api/proto/peopleb\x06proto3"

var (
	file_api_proto_people_people_proto_rawDescOnce sync.Once
	file_api_proto_people_people_proto_rawDescData []byte
)

func file_api_proto_people_people_proto_rawDescGZIP() []byte {
	file_api_proto_people_people_proto_rawDescOnce.Do(func() {
		file_api_proto_people_people_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_people_people_proto_rawDesc), len(file_api_proto_people_people_proto_rawDesc)))
	})
	return file_api_proto_people_people_proto_rawDescData
}

var file_api_proto_people_people_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_people_people_proto_goTypes = []any{
	(*UserProfile)(nil),                // 0: people.UserProfile
	(*SearchPeopleRequest)(nil),        // 1: people.SearchPeopleRequest
	(*SearchPeopleResponse)(nil),       // 2: people.SearchPeopleResponse
	(*GetRecommendationsRequest)(nil),  // 3: people.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil), // 4: people.GetRecommendationsResponse
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_api_proto_people_people_proto_depIdxs = []int32{
	5, // 0: people.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: people.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: people.SearchPeopleResponse.results:type_name -> people.UserProfile
	0, // 3: people.GetRecommendationsResponse.recommendations:type_name -> people.UserProfile
	1, // 4: people.PeopleService.SearchPeople:input_type -> people.SearchPeopleRequest
	3, // 5: people.PeopleService.GetRecommendations:input_type -> people.GetRecommendationsRequest
	2, // 6: people.PeopleService.SearchPeople:output_type -> people.SearchPeopleResponse
	4, // 7: people.PeopleService.GetRecommendations:output_type -> people.GetRecommendationsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_people_people_proto_init() }
func file_api_proto_people_people_proto_init() {
	if File_api_proto_people_people_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_people_people_proto_rawDesc), len(file_api_proto_people_people_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_people_people_proto_goTypes,
		DependencyIndexes: file_api_proto_people_people_proto_depIdxs,
		MessageInfos:      file_api_proto_people_people_proto_msgTypes,
	}.Build()
	File_api_proto_people_people_proto = out.File
	file_api_proto_people_people_proto_goTypes = nil
	file_api_proto_people_people_proto_depIdxs = nil
}
