// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/dashboard/dashboard.proto

package dashboard

import (
	feedback "ethos/api/proto/feedback"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DashboardStats represents aggregated statistics
type DashboardStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FeedbackGiven   int32                  `protobuf:"varint,1,opt,name=feedback_given,json=feedbackGiven,proto3" json:"feedback_given,omitempty"`
	Comments        int32                  `protobuf:"varint,2,opt,name=comments,proto3" json:"comments,omitempty"`
	AdditionalStats map[string]int32       `protobuf:"bytes,3,rep,name=additional_stats,json=additionalStats,proto3" json:"additional_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DashboardStats) Reset() {
	*x = DashboardStats{}
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStats) ProtoMessage() {}

func (x *DashboardStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStats.ProtoReflect.Descriptor instead.
func (*DashboardStats) Descriptor() ([]byte, []int) {
	return file_api_proto_dashboard_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardStats) GetFeedbackGiven() int32 {
	if x != nil {
		return x.FeedbackGiven
	}
	return 0
}

func (x *DashboardStats) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *DashboardStats) GetAdditionalStats() map[string]int32 {
	if x != nil {
		return x.AdditionalStats
	}
	return nil
}

// DashboardSnapshot represents a dashboard view
type DashboardSnapshot struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	RecentFeedback   []*feedback.FeedbackItem `protobuf:"bytes,1,rep,name=recent_feedback,json=recentFeedback,proto3" json:"recent_feedback,omitempty"`
	Stats            *DashboardStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	SuggestedActions []string                 `protobuf:"bytes,3,rep,name=suggested_actions,json=suggestedActions,proto3" json:"suggested_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DashboardSnapshot) Reset() {
	*x = DashboardSnapshot{}
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSnapshot) ProtoMessage() {}

func (x *DashboardSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSnapshot.ProtoReflect.Descriptor instead.
func (*DashboardSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_dashboard_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardSnapshot) GetRecentFeedback() []*feedback.FeedbackItem {
	if x != nil {
		return x.RecentFeedback
	}
	return nil
}

func (x *DashboardSnapshot) GetStats() *DashboardStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *DashboardSnapshot) GetSuggestedActions() []string {
	if x != nil {
		return x.SuggestedActions
	}
	return nil
}

// GetDashboardRequest requests dashboard data
type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dashboard_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetDashboardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetDashboardResponse returns dashboard snapshot
type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *DashboardSnapshot     `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dashboard_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dashboard_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetDashboardResponse) GetSnapshot() *DashboardSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_api_proto_dashboard_dashboard_proto protoreflect.FileDescriptor

const file_api_proto_dashboard_dashboard_proto_rawDesc = "" +
	"\n" +
	"#api/proto/dashboard/dashboard.proto\x12\tdashboard\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!api/proto/feedback/feedback.proto\"\xf2\x01\n" +
	"\x0eDashboardStats\x12%\n" +
	"\x0efeedback_given\x18\x01 \x01(\x05R\rfeedbackGiven\x12\x1a\n" +
	"\bcomments\x18\x02 \x01(\x05R\bcomments\x12Y\n" +
	"\x10additional_stats\x18\x03 \x03(\v2..dashboard.DashboardStats.AdditionalStatsEntryR\x0fadditionalStats\x1aB\n" +
	"\x14AdditionalStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xb2\x01\n" +
	"\x11DashboardSnapshot\x12?\n" +
	"\x0frecent_feedback\x18\x01 \x03(\v2\x16.feedback.FeedbackItemR\x0erecentFeedback\x12/\n" +
	"\x05stats\x18\x02 \x01(\v2\x19.dashboard.DashboardStatsR\x05stats\x12+\n" +
	"\x11suggested_actions\x18\x03 \x03(\tR\x10suggestedActions\".\n" +
	"\x13GetDashboardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"P\n" +
	"\x14GetDashboardResponse\x128\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1c.dashboard.DashboardSnapshotR\bsnapshot2c\n" +
	"\x10DashboardService\x12O\n" +
	"\fGetDashboard\x12\x1e.dashboard.GetDashboardRequest\x1a\x1f.dashboard.GetDashboardResponseB\x1bZ\x19ethos/api/proto/dashboardb\x06proto3"

var (
	file_api_proto_dashboard_dashboard_proto_rawDescOnce sync.Once
	file_api_proto_dashboard_dashboard_proto_rawDescData []byte
)

func file_api_proto_dashboard_dashboard_proto_rawDescGZIP() []byte {
	file_api_proto_dashboard_dashboard_proto_rawDescOnce.Do(func() {
		file_api_proto_dashboard_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dashboard_dashboard_proto_rawDesc), len(file_api_proto_dashboard_dashboard_proto_rawDesc)))
	})
	return file_api_proto_dashboard_dashboard_proto_rawDescData
}

var file_api_proto_dashboard_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_dashboard_dashboard_proto_goTypes = []any{
	(*DashboardStats)(nil),        // 0: dashboard.DashboardStats
	(*DashboardSnapshot)(nil),     // 1: dashboard.DashboardSnapshot
	(*GetDashboardRequest)(nil),   // 2: dashboard.GetDashboardRequest
	(*GetDashboardResponse)(nil),  // 3: dashboard.GetDashboardResponse
	nil,                           // 4: dashboard.DashboardStats.AdditionalStatsEntry
	(*feedback.FeedbackItem)(nil), // 5: feedback.FeedbackItem
}
var file_api_proto_dashboard_dashboard_proto_depIdxs = []int32{
	4, // 0: dashboard.DashboardStats.additional_stats:type_name -> dashboard.DashboardStats.AdditionalStatsEntry
	5, // 1: dashboard.DashboardSnapshot.recent_feedback:type_name -> feedback.FeedbackItem
	0, // 2: dashboard.DashboardSnapshot.stats:type_name -> dashboard.DashboardStats
	1, // 3: dashboard.GetDashboardResponse.snapshot:type_name -> dashboard.DashboardSnapshot
	2, // 4: dashboard.DashboardService.GetDashboard:input_type -> dashboard.GetDashboardRequest
	3, // 5: dashboard.DashboardService.GetDashboard:output_type -> dashboard.GetDashboardResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_dashboard_dashboard_proto_init() }
func file_api_proto_dashboard_dashboard_proto_init() {
	if File_api_proto_dashboard_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dashboard_dashboard_proto_rawDesc), len(file_api_proto_dashboard_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dashboard_dashboard_proto_goTypes,
		DependencyIndexes: file_api_proto_dashboard_dashboard_proto_depIdxs,
		MessageInfos:      file_api_proto_dashboard_dashboard_proto_msgTypes,
	}.Build()
	File_api_proto_dashboard_dashboard_proto = out.File
	file_api_proto_dashboard_dashboard_proto_goTypes = nil
	file_api_proto_dashboard_dashboard_proto_depIdxs = nil
}
