// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/notifications/notifications.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationType represents types of notifications
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED       NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_FEEDBACK_REPLY    NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_FEEDBACK_RECEIVED NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_NEW_COMMENT       NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_SYSTEM_ALERT      NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_REMINDER          NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_OTHER             NotificationType = 6
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_FEEDBACK_REPLY",
		2: "NOTIFICATION_TYPE_FEEDBACK_RECEIVED",
		3: "NOTIFICATION_TYPE_NEW_COMMENT",
		4: "NOTIFICATION_TYPE_SYSTEM_ALERT",
		5: "NOTIFICATION_TYPE_REMINDER",
		6: "NOTIFICATION_TYPE_OTHER",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":       0,
		"NOTIFICATION_TYPE_FEEDBACK_REPLY":    1,
		"NOTIFICATION_TYPE_FEEDBACK_RECEIVED": 2,
		"NOTIFICATION_TYPE_NEW_COMMENT":       3,
		"NOTIFICATION_TYPE_SYSTEM_ALERT":      4,
		"NOTIFICATION_TYPE_REMINDER":          5,
		"NOTIFICATION_TYPE_OTHER":             6,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_notifications_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_api_proto_notifications_notifications_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

// Notification represents a notification
type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Type           NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=notifications.NotificationType" json:"type,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Read           bool                   `protobuf:"varint,4,opt,name=read,proto3" json:"read,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// NotificationPreferences represents delivery preferences
type NotificationPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         bool                   `protobuf:"varint,1,opt,name=email,proto3" json:"email,omitempty"`
	Push          bool                   `protobuf:"varint,2,opt,name=push,proto3" json:"push,omitempty"`
	InApp         bool                   `protobuf:"varint,3,opt,name=in_app,json=inApp,proto3" json:"in_app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationPreferences) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *NotificationPreferences) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

func (x *NotificationPreferences) GetInApp() bool {
	if x != nil {
		return x.InApp
	}
	return false
}

// GetNotificationsRequest requests paginated notifications
type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetNotificationsResponse returns paginated notifications
type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// GetPreferencesRequest requests notification preferences
type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetPreferencesResponse returns notification preferences
type GetPreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *GetPreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UpdatePreferencesRequest updates notification preferences
type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   *NotificationPreferences `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UpdatePreferencesResponse confirms preference update
type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notifications_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notifications_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_api_proto_notifications_notifications_proto protoreflect.FileDescriptor

const file_api_proto_notifications_notifications_proto_rawDesc = "" +
	"\n" +
	"+api/proto/notifications/notifications.proto\x12\rnotifications\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\fNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.notifications.NotificationTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Z\n" +
	"\x17NotificationPreferences\x12\x14\n" +
	"\x05email\x18\x01 \x01(\bR\x05email\x12\x12\n" +
	"\x04push\x18\x02 \x01(\bR\x04push\x12\x15\n" +
	"\x06in_app\x18\x03 \x01(\bR\x05inApp\"`\n" +
	"\x17GetNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x96\x01\n" +
	"\x18GetNotificationsResponse\x12A\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1b.notifications.NotificationR\rnotifications\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"b\n" +
	"\x16GetPreferencesResponse\x12H\n" +
	"\vpreferences\x18\x01 \x01(\v2&.notifications.NotificationPreferencesR\vpreferences\"}\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12H\n" +
	"\vpreferences\x18\x02 \x01(\v2&.notifications.NotificationPreferencesR\vpreferences\"e\n" +
	"\x19UpdatePreferencesResponse\x12H\n" +
	"\vpreferences\x18\x01 \x01(\v2&.notifications.NotificationPreferencesR\vpreferences*\x88\x02\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" NOTIFICATION_TYPE_FEEDBACK_REPLY\x10\x01\x12'\n" +
	"#NOTIFICATION_TYPE_FEEDBACK_RECEIVED\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_TYPE_NEW_COMMENT\x10\x03\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_SYSTEM_ALERT\x10\x04\x12\x1e\n" +
	"\x1aNOTIFICATION_TYPE_REMINDER\x10\x05\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_OTHER\x10\x062\xc1\x02\n" +
	"\x13NotificationService\x12c\n" +
	"\x10GetNotifications\x12&.notifications.GetNotificationsRequest\x1a'.notifications.GetNotificationsResponse\x12]\n" +
	"\x0eGetPreferences\x12$.notifications.GetPreferencesRequest\x1a%.notifications.GetPreferencesResponse\x12f\n" +
	"\x11UpdatePreferences\x12'.notifications.UpdatePreferencesRequest\x1a(.notifications.UpdatePreferencesResponseB\x1fZ\x1dethos/api/proto/notificationsb\x06proto3"

var (
	file_api_proto_notifications_notifications_proto_rawDescOnce sync.Once
	file_api_proto_notifications_notifications_proto_rawDescData []byte
)

func file_api_proto_notifications_notifications_proto_rawDescGZIP() []byte {
	file_api_proto_notifications_notifications_proto_rawDescOnce.Do(func() {
		file_api_proto_notifications_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notifications_notifications_proto_rawDesc), len(file_api_proto_notifications_notifications_proto_rawDesc)))
	})
	return file_api_proto_notifications_notifications_proto_rawDescData
}

var file_api_proto_notifications_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_notifications_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_notifications_notifications_proto_goTypes = []any{
	(NotificationType)(0),             // 0: notifications.NotificationType
	(*Notification)(nil),              // 1: notifications.Notification
	(*NotificationPreferences)(nil),   // 2: notifications.NotificationPreferences
	(*GetNotificationsRequest)(nil),   // 3: notifications.GetNotificationsRequest
	(*GetNotificationsResponse)(nil),  // 4: notifications.GetNotificationsResponse
	(*GetPreferencesRequest)(nil),     // 5: notifications.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),    // 6: notifications.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),  // 7: notifications.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil), // 8: notifications.UpdatePreferencesResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_api_proto_notifications_notifications_proto_depIdxs = []int32{
	0, // 0: notifications.Notification.type:type_name -> notifications.NotificationType
	9, // 1: notifications.Notification.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: notifications.GetNotificationsResponse.notifications:type_name -> notifications.Notification
	2, // 3: notifications.GetPreferencesResponse.preferences:type_name -> notifications.NotificationPreferences
	2, // 4: notifications.UpdatePreferencesRequest.preferences:type_name -> notifications.NotificationPreferences
	2, // 5: notifications.UpdatePreferencesResponse.preferences:type_name -> notifications.NotificationPreferences
	3, // 6: notifications.NotificationService.GetNotifications:input_type -> notifications.GetNotificationsRequest
	5, // 7: notifications.NotificationService.GetPreferences:input_type -> notifications.GetPreferencesRequest
	7, // 8: notifications.NotificationService.UpdatePreferences:input_type -> notifications.UpdatePreferencesRequest
	4, // 9: notifications.NotificationService.GetNotifications:output_type -> notifications.GetNotificationsResponse
	6, // 10: notifications.NotificationService.GetPreferences:output_type -> notifications.GetPreferencesResponse
	8, // 11: notifications.NotificationService.UpdatePreferences:output_type -> notifications.UpdatePreferencesResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_notifications_notifications_proto_init() }
func file_api_proto_notifications_notifications_proto_init() {
	if File_api_proto_notifications_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notifications_notifications_proto_rawDesc), len(file_api_proto_notifications_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notifications_notifications_proto_goTypes,
		DependencyIndexes: file_api_proto_notifications_notifications_proto_depIdxs,
		EnumInfos:         file_api_proto_notifications_notifications_proto_enumTypes,
		MessageInfos:      file_api_proto_notifications_notifications_proto_msgTypes,
	}.Build()
	File_api_proto_notifications_notifications_proto = out.File
	file_api_proto_notifications_notifications_proto_goTypes = nil
	file_api_proto_notifications_notifications_proto_depIdxs = nil
}
